### ISSUE TITLE
Async triggers need to be updated ballerina update 2

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/asyncapi-triggers#111]
## Description
Async triggers need to be updated ballerina update 2.  

## Steps

1. go inside an async trigger.
2. rm Dependencies.toml
3. try to build with 2201.2.*
4. Fix errors
e.g: Update connector initializations inside the trigger
5. Bump versions & push the latest to DEV

**Comment by LakshanSS** [comment]
Closing since this is already done
